config/routes.rb
Appideas::Application.routes.draw do
  resources :users

  root 'ideas#index'

  resources :keywords
  resources :ideas
  resources :users
  resources :sessions, only: [:new, :create]

  get 'admin/keywords', to: 'keywords#admin'
  get 'admin/ideas', to: 'ideas#admin'
  get 'signup', to: 'users#new'
  get 'signin', to: 'sessions#new'
  delete 'signout', to: 'sessions#destroy'
  
resources :ideas do
  member do
    put "like", to: "ideas#upvote"
    put "dislike", to: "ideas#downvote"
  end
end

end

app/models/idea.rb
class Idea < ActiveRecord::Base
  acts_as_commentable
  acts_as_votable

  validates :name, presence: true
  validates :desc, presence: true

  has_many :idea_keywords, :dependent => :destroy
  has_many :keywords, through: :idea_keywords

end

app/controllers/ideas_controller.rb
require 'rails_autolink'

class IdeasController < ApplicationController

  before_action :set_idea, only: [:show, :edit, :update, :destroy]
  before_action :set_keywords
  before_action :ensure_that_signed_in, only: [:upvote, :downvote]
  #before_action :set_comments

  # GET /ideas
  # GET /ideas.json
  def index
    kw = Keyword.find(params[:kw].to_i) unless params[:kw].nil?
    @ideas = Idea.all

    if kw.nil?
      @keywordname = ""
      @indexideas = Idea.all.order('name ASC')
    else
      @keywordname = kw.name  + " - "
      @indexideas = Idea.all.order('name ASC').select{ |i| i.keywords.include?(kw)}
    end
    # This section adds filtering to keyword bar, customer doesn't want it anymore
=begin
    @keywords = []
    @indexideas.each do |i|
        i.keywords.each do |k|
          @keywords << k
        end
      order = params[:order] || 'id'
      case order
        when 'id' then @indexideas.sort_by!{ |b| b.id }
      end
    end
=end
    # replaced by @keywords = Keyword.all
    @keywords = Keyword.all

#    @keywords = @keywords.each_with_object([]){ |kv, result| result << kv unless result.include?(kv); result }
    @keywords = @keywords.uniq
    @words = @keywords unless kw.nil?

    order = params[:order] || 'name'

    case order
    when 'name' then @words.order('name DESC')# @words.sort_by!{ |b| b.name }
    end

    # this new idea needed when there is no related keyword to form new idea partial
    @idea = Idea.new
  end


  # GET /ideas/1
  # GET /ideas/1.json
  def show
    @idea = Idea.find(params[:id])
    # get comments from db
    @comments = Comment.find_comments_for_commentable( "Idea", @idea.id )
    @keywords = @idea.keywords
    #@words = @keywords
    @all = Keyword.all
   # keyword_id = params[:keyword_id]
=begin
    remove_id = params[:remove_id]
    unless remove_id.nil? or remove_id.empty?
      #keyword = Keyword.find(remove_id)
      @idea.keywords.delete(remove_id)
    end
    unless keyword_id.nil? or keyword_id.empty?
      keyword = Keyword.find(keyword_id)
      @idea.keywords << keyword
      redirect_to idea_path(@idea)
    end
=end
    order = params[:order] || 'name'

    case order
    when 'name' then @all.sort_by!{ |b| b.name }
    end

  end


  # GET /ideas/new
  def new
    @idea = Idea.new
    @keywords = Keyword.all

    order = params[:order] || 'name'

    case order
    when 'name' then @keywords.sort_by!{ |b| b.name }
    end
  end

  # GET /ideas/1/edit
  def edit
    @all = Keyword.all

    order = params[:order] || 'name'

    @keywords = case order
    when 'name' then Keyword.all.order("? ASC", order)
    else Keywork.all
    end
  end

  # POST /ideas # POST /ideas.json
  def create
    @idea = Idea.new(idea_params)
    keyword_ids = params[:idea][:keyword_ids]
    keywords = Keyword.select do |k|
        keyword_ids.include? k.id.to_s
    end

    if @idea.save
      @idea.keywords << keywords
      redirect_to @idea
    else
      @keywords = Keyword.all
      respond_to do |format|
        format.html { render action: 'new' }
        format.json { render json: @idea.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /ideas/1
  # PATCH/PUT /ideas/1.json
  def update
    @idea = Idea.find(params[:id])
    # get user to add comment, for now use dummy user
    user = User.first
    comment_body = params[:comment_body]
    unless comment_body.nil? or comment_body.empty?
      comment = Comment.build_from(@idea, user.id, comment_body)
      comment.save
    end
    old_keywords = @idea.keywords


    if(params.has_key?(:idea))
      keyword_ids = params[:idea][:keyword_ids]
      keywords =
        Keyword.select do |k|
        keyword_ids.include? k.id.to_s
        end
      keywords.each do |kw|
        unless old_keywords.include? kw
          @idea.keywords << kw
        end
      end

      old_keywords.each do |old|
        IdeaKeyword.find_by_keyword_id_and_idea_id(old.id, @idea.id).destroy unless keywords.include? old
      end

      respond_to do |format|
        if @idea.update(idea_params)
          format.html { redirect_to @idea, notice: 'Idea was successfully updated.' }
          format.json { head :no_content }
        else
          @keywords = Keyword.all
          @all = Keyword.all
          # Any other options to set comments? It shows now idea's comments after trying to update unvalid idea.
          set_comments
          format.html { render action: 'edit' }
          format.json { render json: @idea.errors, status: :unprocessable_entity }
        end
      end
    else
      redirect_to @idea
    end
  end

  # DELETE /ideas/1
  # DELETE /ideas/1.json
  def destroy
    @idea.destroy
    respond_to do |format|
      format.html { redirect_to ideas_url }
      format.json { head :no_content }
    end
  end

  def upvote
    @idea = Idea.find(params[:id])
    @idea.liked_by current_user
    redirect_to :back
  end

  def downvote
    @idea = Idea.find(params[:id])
    @idea.downvote_from current_user
    redirect_to :back
  end

  def admin
    @ideas = Idea.all
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_idea
    @idea = Idea.find(params[:id])
  end

  def set_keywords
    order = params[:order] || 'name'

    @words = case order
    when 'name' then Keyword.order("? ASC", order)
    else Keyword.all
    end
  end

  def set_comments
    idea = Idea.find(params[:id])
    @comments = Comment.find_comments_for_commentable( "Idea", idea.id )
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def idea_params
    params.require(:idea).permit(:name, :desc)
  end

end

app/helpers/ideas_helper.rb
module IdeasHelper
end

app/views/ideas/_form.html.haml
= form_for @idea, :html => { :class => 'form-vertical' } do |f|
  - @idea.errors.full_messages.each do |msg|
    %p
      %font{color: "red"}
        = msg
  .control-group
    = f.label :name, :class => 'control-label'
    .controls
      = f.text_field :name, :class => 'text_field'
  .control-group
    = f.label "Description", :class => 'control-label', type:'desc'
    .controls
      = f.text_area :desc, :class => 'text_area', type:'text'
  .control-group
    = f.label :keywords, :class => 'control-label'
    .controls
      = f.collection_check_boxes(:keyword_ids, @keywords, :id, :name, {}, {:class => 'checkbox'} ) { |input| input.label(:class => 'checkbox') { input.check_box + input.text } }
  .form-actions
    = f.submit nil, :class => 'btn btn-primary'
    = link_to t('.cancel', :default => t("helpers.links.cancel")), ideas_path, :class => 'btn'

app/views/ideas/admin.html.haml
- model_class = Idea
.page-header
  %h1=t '.title', :default => model_class.model_name.human.pluralize.titleize
%table.table.table-striped
  %thead
    %tr
      %th= model_class.human_attribute_name(:id)
      %th= model_class.human_attribute_name(:name)
      %th= model_class.human_attribute_name(:desc)
      %th= model_class.human_attribute_name(:created_at)
      %th=t '.actions', :default => t("helpers.actions")
  %tbody
    - @ideas.reverse.each do |idea|
      %tr
        %td= link_to idea.id, idea_path(idea)
        %td= idea.name
        %td= idea.desc
        %td=l idea.created_at
        %td
          = link_to t('.edit', :default => t("helpers.links.edit")), edit_idea_path(idea), :class => 'btn btn-mini'
          = link_to t('.destroy', :default => t("helpers.links.destroy")), idea_path(idea), :method => :delete, :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-mini btn-danger'

= link_to t('.new', :default => t("helpers.links.new")), new_idea_path, :class => 'btn btn-primary'

app/views/ideas/edit.html.haml
- model_class = Idea

= render :partial => "form"

app/views/ideas/index.html.haml
%link{:href => "//netdna.bootstrapcdn.com/bootstrap/3.0.0/css/bootstrap-glyphicons.css", :rel => "stylesheet"}/
- model_class = Idea
.page-body
  %strong=t '.title', :default => @keywordname + model_class.model_name.human.pluralize.titleize
%table.table.details{:id => "comment_table"}

- if @indexideas.empty?
  %br
  %b= "No ideas yet, why don't you add one?"
  %p
    = render :partial => "form"

%table.table{:id => "comment_table"}
  %tbody

    - @indexideas.each do |idea|
      %tr
        %td.ivote{style: "width:10%"}
          = link_to "", like_idea_path(idea), method: :put, :class => 'glyphicon glyphicon-chevron-up btn-default'
          %br
          = idea.upvotes.size-idea.downvotes.size
          %br
          = link_to "", dislike_idea_path(idea), method: :put, :class => 'glyphicon glyphicon-chevron-down btn-default'
        %td
          -#= link_to idea.id, idea_path(idea)
          %h4= link_to idea.name, idea
          %p
            =simple_format(auto_link (truncate(idea.desc, length: 300) + link_to(" Show More", idea)))
          -#%td=l idea.created_at
          -#%td
          - idea.keywords.each_with_index do |k, i|
            - if i==idea.keywords.size-1
              = link_to k.name, ideas_path(:kw => k)
            - else
              = link_to k.name+',', ideas_path(:kw => k)


        -#%td
          = link_to t('.edit', :default => t("helpers.links.edit")), edit_idea_path(idea), :class => 'btn btn-mini'
          = link_to t('.destroy', :default => t("helpers.links.destroy")), idea_path(idea), :method => :delete, :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-mini btn-danger'

-# = link_to t('.new', :default => t("helpers.links.new")), new_idea_path, :class => 'btn btn-primary'

app/views/ideas/new.html.haml
- model_class = Idea
.page-body
= render :partial => "form"

app/views/ideas/show.html.haml
.body
  %link{:href => "//netdna.bootstrapcdn.com/bootstrap/3.0.0/css/bootstrap-glyphicons.css", :rel => "stylesheet"}/
  - model_class = Idea

  -#.page-header
    -#%h1=t '.title', :default => model_class.model_name.human.titleize
  %table.table{:id => "comment_table"}
    %tr
      %td.vote{style: "width:10%" }
        = link_to "", like_idea_path(@idea), method: :put, :class => 'glyphicon glyphicon-chevron-up btn-default'
        %br
        = @idea.upvotes.size-@idea.downvotes.size
        %br
        = link_to "", dislike_idea_path(@idea), method: :put, :class => 'glyphicon glyphicon-chevron-down btn-default'
      %td.details
        %p
          %h3
            = @idea.name
        %p
          -# TODO: textarea formatting now includes returns
          = simple_format (auto_link (@idea.desc))

        %strong Related Keywords:
        %br
        - @keywords.each_with_index do |k, i|
          - if i==@keywords.size-1
            = link_to k.name, ideas_path(:kw => k)
          - else
            = link_to k.name+',', ideas_path(:kw => k)


  .form-actions
    = link_to t('.back', :default => t("helpers.links.back")), ideas_path, :class => 'btn'
    = link_to t('.edit', :default => t("helpers.links.edit")), edit_idea_path(@idea), :class => 'btn'
    -#= link_to t('.destroy', :default => t("helpers.links.destroy")), idea_path(@idea), :method => "delete", :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-danger'