config/routes.rb
Appideas::Application.routes.draw do
  resources :users

  root 'ideas#index'

  resources :keywords
  resources :ideas
  resources :users
  resources :sessions, only: [:new, :create]

  get 'admin/keywords', to: 'keywords#admin'
  get 'admin/ideas', to: 'ideas#admin'
  get 'signup', to: 'users#new'
  get 'signin', to: 'sessions#new'
  delete 'signout', to: 'sessions#destroy'
  
resources :ideas do
  member do
    put "like", to: "ideas#upvote"
    put "dislike", to: "ideas#downvote"
  end
end

end

app/models/keyword.rb
class Keyword < ActiveRecord::Base
  validates_presence_of :name
  validates :name, uniqueness: true

  has_many :idea_keywords, :dependent => :destroy
  has_many :ideas, through: :idea_keywords
end

app/controllers/keywords_controller.rb
class KeywordsController < ApplicationController
  before_action :set_keyword, only: [:show, :edit, :update, :destroy]
  before_action :set_keywords

  # GET /keywords
  # GET /keywords.json
  def index
    @keywords = Keyword.all

    order = params[:order] || 'name'

    case order
    when 'name' then @keywords.sort_by!{ |b| b.name }
    end

  end

  # GET /keywords/1
  # GET /keywords/1.json
  def show
  end

  # GET /keywords/new
  def new
    @keyword = Keyword.new
  end

  # GET /keywords/1/edit
  def edit
  end

  # POST /keywords
  # POST /keywords.json
  def create
    @keyword = Keyword.new(keyword_params)

    respond_to do |format|
      if @keyword.save
        format.html { redirect_to @keyword, notice: 'Keyword was successfully created.' }
        format.json { render action: 'show', status: :created, location: @keyword }
      else
        format.html { render action: 'new' }
        format.json { render json: @keyword.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /keywords/1
  # PATCH/PUT /keywords/1.json
  def update
    respond_to do |format|
      if @keyword.update(keyword_params)
        format.html { redirect_to @keyword, notice: 'Keyword was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @keyword.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /keywords/1
  # DELETE /keywords/1.json
  def destroy
    @keyword.destroy
    respond_to do |format|
      format.html { redirect_to keywords_url }
      format.json { head :no_content }
    end
  end

  def admin
    @keywords = Keyword.all
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_keyword
    @keyword = Keyword.find(params[:id])
  end

  def set_keywords
    @words = Keyword.all
    order = params[:order] || 'name'

    case order
    when 'name' then @words.sort_by!{ |b| b.name }
    end
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def keyword_params
    params.require(:keyword).permit(:name, :concrete)
  end

end

app/helpers/keywords_helper.rb
module KeywordsHelper
end

app/views/keywords/_form.html.haml
= form_for @keyword, :html => { :class => 'form-horizontal' } do |f|
  - @keyword.errors.full_messages.each do |msg|
    %p
      %font{color: "red"}
        = msg
  .control-group
    = f.label :name, :class => 'control-label'
    .controls
      = f.text_field :name, :class => 'text_field'
  .control-group
    = f.label :concrete, :class => 'control-label'
    .controls
      = f.text_field :concrete, :class => 'text_field'
  .form-actions
    = f.submit nil, :class => 'btn btn-primary'
    = link_to t('.cancel', :default => t("helpers.links.cancel")), keywords_path, :class => 'btn'

app/views/keywords/admin.html.haml
- model_class = Keyword
.page-header
  %h1=t '.title', :default => model_class.model_name.human.pluralize.titleize
%table.table.table-striped
  %thead
    %tr
      %th= model_class.human_attribute_name(:id)
      %th= model_class.human_attribute_name(:name)
      %th= model_class.human_attribute_name(:concrete)
      %th= model_class.human_attribute_name(:created_at)
      %th=t '.actions', :default => t("helpers.actions")
  %tbody
    - @keywords.each do |keyword|
      %tr
        %td= link_to keyword.id, keyword_path(keyword)
        %td= keyword.name
        %td= keyword.concrete
        %td=l keyword.created_at
        %td
          = link_to t('.edit', :default => t("helpers.links.edit")), edit_keyword_path(keyword), :class => 'btn btn-mini'
          = link_to t('.destroy', :default => t("helpers.links.destroy")), keyword_path(keyword), :method => :delete, :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-mini btn-danger'

= link_to t('.new', :default => t("helpers.links.new")), new_keyword_path, :class => 'btn btn-primary'

app/views/keywords/edit.html.haml
- model_class = Keyword
.page-header
  %h1=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize
= render :partial => "form"

app/views/keywords/index.html.haml
- model_class = Keyword
.page-header
  %h1=t '.title', :default => model_class.model_name.human.pluralize.titleize
%table.table.table-striped
  %thead
    %tr
      %th= model_class.human_attribute_name(:id)
      %th= model_class.human_attribute_name(:name)
      %th= model_class.human_attribute_name(:concrete)
      %th= model_class.human_attribute_name(:created_at)
      %th=t '.actions', :default => t("helpers.actions")
  %tbody
    - @keywords.each do |keyword|
      %tr
        %td= link_to keyword.id, keyword_path(keyword)
        %td= keyword.name
        %td= keyword.concrete
        %td=l keyword.created_at
        %td
          = link_to t('.edit', :default => t("helpers.links.edit")), edit_keyword_path(keyword), :class => 'btn btn-mini'
          = link_to t('.destroy', :default => t("helpers.links.destroy")), keyword_path(keyword), :method => :delete, :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-mini btn-danger'

= link_to t('.new', :default => t("helpers.links.new")), new_keyword_path, :class => 'btn btn-primary'

app/views/keywords/new.html.haml
- model_class = Keyword
.page-header
  %h1=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize
= render :partial => "form"