config/routes.rb
Appideas::Application.routes.draw do
  resources :users

  root 'ideas#index'

  resources :keywords
  resources :ideas
  resources :users
  resources :sessions, only: [:new, :create]

  get 'admin/keywords', to: 'keywords#admin'
  get 'admin/ideas', to: 'ideas#admin'
  get 'signup', to: 'users#new'
  get 'signin', to: 'sessions#new'
  delete 'signout', to: 'sessions#destroy'
  
resources :ideas do
  member do
    put "like", to: "ideas#upvote"
    put "dislike", to: "ideas#downvote"
  end
end

end

app/views/layouts/application.html.haml
!!! 5
%html(lang="en")
  %head
    %meta(charset="utf-8")
    %meta(http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1")
    %meta(name="viewport" content="width=device-width, initial-scale=1.0")
    %title= content_for?(:title) ? yield(:title) : "Appideas"
    = csrf_meta_tags
    / Le HTML5 shim, for IE6-8 support of HTML elements
    /[if lt IE 9]
      = javascript_include_tag "//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js"
    = stylesheet_link_tag "application", :media => "all"
    = favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144'
    = favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114'
    = favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72'
    = favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png'
    = favicon_link_tag 'favicon.ico', :rel => 'shortcut icon'
    = javascript_include_tag "application"
    -# Glypicons link
    %link{:href => "//netdna.bootstrapcdn.com/bootstrap/3.0.0/css/bootstrap-glyphicons.css", :rel => "stylesheet"}/


  %header
    %navbar.navbar-default
      %ul.nav.nav-tabs
        -# %li= link_to image_tag( 'logo40.png'), ideas_path
        %li= link_to "Ideas", ideas_path
        %li= link_to "New Idea", new_idea_path
        - if not current_user.nil?
          %li.small= link_to current_user.username unless current_user.nil?
          %li.small= link_to 'Signout', signout_path, method: :delete
        - else
          %li.small= link_to 'Signin', signin_path
          %li.small= link_to 'Signup', signup_path
  %body

    .container-fluid

      .row-fluid
        .span3#left-sidebar
          .well.sidebar-nav
            %ul.nav.nav-list
              %li.nav-header Keywords
              - @words.each do |keyword|
                %span
                  %li
                    = link_to keyword.name, ideas_path(:kw => keyword)
                  /
                    - if request.path =~ /\/ideas\/\d+$/
                      = link_to t('.update', :default => ""), idea_path(id: request.path.match(/\d+/i), remove_id: keyword.id), :class => 'glyphicon glyphicon-remove btn-default'
            /
              %p
              - if request.path.match(/\/ideas\/\d+$/)
                .btn-group
                  %button.btn.btn-default.btn-sm.dropdown-toggle{"data-toggle" => "dropdown", type: "button"}
                    Add Keyword
                    %span.caret
                  %ul.dropdown-menu{role: "manu"}
                    - @all.each do |keyword|
                      %li
                        - if @words.include? keyword
                          = link_to raw('<i class="icon-ok icon-green"></i>') + keyword.name, ""
                        - else
                          = link_to keyword.name, idea_path(id: request.path.match(/\d+/i), keyword_id: keyword.id)
        .span6#main-content
          = bootstrap_flash
          = yield
        .span3#right-sidebar
          - if request.path =~ /\/ideas\/\d+$/
            %table.table.table-bordered.table-striped{:id => "comment_table"}
              %tbody
                ='Comments:'
                - @comments.each do |comment|
                  %tr
                    %td
                      %small{:id => "comment_cell"}
                        = comment.created_at
                      %br
                      = simple_format (auto_link (comment.body))
            = form_tag(request.path, :method => :patch) do
              = text_area_tag :comment_body
              = submit_tag "Comment"

      %footer
        %p &copy; tktl-appideas